Etho-5/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo.</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Etho-5/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jogador foi eliminado.</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

Etho-5/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o round que o jogador participou.</description>
    <inlineHelpText>Usado para informar o round que o jogador participou.</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Etho-5/force-app/main/default/classes/RoundsSelectorTest.cls
@isTest
public with sharing class RoundsSelectorTest {

    @TestSetup
    static void setup(){
        Round__c round = new Round__c();
        insert round;
    }

    @isTest
    static void test1() {
        Map<Id, Round__c> roundsMap = new Map<Id, Round__c>([SELECT Id FROM Round__c]);
        System.debug('Limits BEFORE: ' + Limits.getQueries());

        Test.startTest();
        List<Round__c> rounds = RoundsSelector.selectByRoundsIdsWithJogadores(roundsMap.keySet());
        System.debug('Limits INSIDE: ' + Limits.getQueries());
        Test.stopTest();

        System.debug('Limits AFTER: ' + Limits.getQueries());

        System.assertEquals(roundsMap.size(), rounds.size());
    }

    @isTest
    static void test2() {
        List<Round__c> rounds = [SELECT Id FROM Round__c];
        Id roundId = rounds.get(0).Id;
        Id roundId2 = rounds.get(1).Id;
        Set<Id> ids = new Set<Id>{roundId, roundId2};
        Jogador__c jogador1 = new Jogador__c(Round__c = roundId, Eliminado__c = true);
        Jogador__c jogador2 = new Jogador__c(Round__c = roundId, Eliminado__c = false);
        Jogador__c jogador3 = new Jogador__c(Round__c = roundId2, Eliminado__c = true);
        List<Jogador__c> jogadores = new List<Jogador__c>{jogador1, jogador2, jogador3};
        insert jogadores;

        Test.startTest();
        List<Round__c> roundsAux = RoundsSelector.selectByRoundsIdsWithJogadores(ids);
        Test.stopTest();

        for (Round__c round : roundsAux) {
            if (round.Id.equals(roundId2)) {
                System.assertEquals(1, round.Jogadores__r.size(), 'Só deveria ter 1 jogador no round 2.');
            }
            for (Jogador__c jogador : round.Jogadores__r) {
                if (round.Id.equals(roundId)) {
                    System.assertNotEquals(jogador.Id, jogador2.Id, 'Jogador 2 não deveria ter retornado nessa query.');
                } else if (round.Id.equals(roundId2)) {
                    System.assertEquals(jogador.Id, jogador3.Id, 'Brotou algum jogador que não era o 3, deu alguma merda.');
                }
            }
        }
    }
}